[package]
name = "safe_auth"
version = "0.0.1"
description = "SAFE Authenticator CLI"
authors = ["Hunter Lester <guilfordhunter@gmail.com>", "bochaco <gabrielviganotti@gmail.com>", "Josh Wilson <joshuef@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
structopt = "0.2.14"
env_logger = "0.6.0"
#safe_authenticator = { git = "https://github.com/hunterlester/safe_client_libs", branch = "safe_authenticator-0.9.0-upgrades" }
#safe_authenticator = { git = "https://github.com/joshuef/safe_client_libs", branch = "safe_authenticator-0.9.0-upgrades" }
safe_authenticator = { git = "https://github.com/bochaco/safe_client_libs", branch = "safe_authenticator-0.9.0-upgrades" }
safe_core = { git = "https://github.com/bochaco/safe_client_libs", branch = "safe_authenticator-0.9.0-upgrades" }
futures = "0.1.25"

[features]
testing = ["safe_authenticator/testing"]
use-mock-routing = ["safe_authenticator/use-mock-routing"]
default = ["use-mock-routing"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook","user-hooks"]
